package com.pandanav.learning.domain.enums;

public enum NextAction {
    INSERT_REMEDIAL_UNDERSTANDING,
    INSERT_TRAINING_VARIANTS,
    INSERT_TRAINING_REINFORCEMENT,
    INSERT_REMEDIAL_STEP,
    SKIP_CURRENT_STEP,
    REPLAN_SESSION,
    ADVANCE_TO_NEXT_NODE,
    NOOP
}


