package com.pandanav.learning.application.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.pandanav.learning.api.dto.task.RunTaskResponse;
import com.pandanav.learning.application.usecase.RunTaskUseCase;
import com.pandanav.learning.auth.UserContextHolder;
import com.pandanav.learning.domain.enums.TaskStatus;
import com.pandanav.learning.domain.llm.StageContentGenerator;
import com.pandanav.learning.domain.llm.model.StageContent;
import com.pandanav.learning.domain.llm.model.StageGenerationContext;
import com.pandanav.learning.domain.model.AttemptLlmMetadata;
import com.pandanav.learning.domain.model.ConceptNode;
import com.pandanav.learning.domain.model.LearningSession;
import com.pandanav.learning.domain.model.LlmCallLog;
import com.pandanav.learning.domain.model.Mastery;
import com.pandanav.learning.domain.model.Task;
import com.pandanav.learning.domain.repository.ConceptNodeRepository;
import com.pandanav.learning.domain.repository.LlmCallLogRepository;
import com.pandanav.learning.domain.repository.MasteryRepository;
import com.pandanav.learning.domain.repository.SessionRepository;
import com.pandanav.learning.domain.repository.TaskRepository;
import com.pandanav.learning.infrastructure.config.LlmProperties;
import com.pandanav.learning.infrastructure.exception.ConflictException;
import com.pandanav.learning.infrastructure.exception.InternalServerException;
import com.pandanav.learning.infrastructure.exception.NotFoundException;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public class TaskRunnerService implements RunTaskUseCase {

    private final TaskRepository taskRepository;
    private final SessionRepository sessionRepository;
    private final ConceptNodeRepository conceptNodeRepository;
    private final MasteryRepository masteryRepository;
    private final StageContentGenerator stageContentGenerator;
    private final LlmCallLogRepository llmCallLogRepository;
    private final LlmProperties llmProperties;
    private final ObjectMapper objectMapper;

    public TaskRunnerService(
        TaskRepository taskRepository,
        SessionRepository sessionRepository,
        ConceptNodeRepository conceptNodeRepository,
        MasteryRepository masteryRepository,
        StageContentGenerator stageContentGenerator,
        LlmCallLogRepository llmCallLogRepository,
        LlmProperties llmProperties,
        ObjectMapper objectMapper
    ) {
        this.taskRepository = taskRepository;
        this.sessionRepository = sessionRepository;
        this.conceptNodeRepository = conceptNodeRepository;
        this.masteryRepository = masteryRepository;
        this.stageContentGenerator = stageContentGenerator;
        this.llmCallLogRepository = llmCallLogRepository;
        this.llmProperties = llmProperties;
        this.objectMapper = objectMapper;
    }

    @Override
    public RunTaskResponse run(Long taskId) {
        Long userId = UserContextHolder.getUserId();
        Task task = (userId == null
            ? taskRepository.findById(taskId)
            : taskRepository.findByIdAndUserPk(taskId, userId))
            .orElseThrow(() -> new NotFoundException("Session or task not found."));

        if (task.getStatus() == TaskStatus.SUCCEEDED && hasOutput(task.getOutputJson())) {
            return toResponse(task, "CACHED", "Output loaded from existing successful attempt.", parseOutput(task.getOutputJson()));
        }

        if (task.getStatus() == TaskStatus.RUNNING) {
            throw new ConflictException("Task is currently running.");
        }

        if (!task.canRun()) {
            throw new ConflictException("Task is not in a runnable state.");
        }

        Long attemptId = taskRepository.createRunningAttempt(taskId);
        task.markRunning();

        JsonNode generated;
        AttemptLlmMetadata metadata;
        StageContent llmStageContent = null;
        String promptKey = null;
        String generationReason;
        try {
            llmStageContent = generateByLlm(task, userId);
            generated = llmStageContent.content();
            promptKey = llmStageContent.promptKey();
            metadata = new AttemptLlmMetadata(
                llmStageContent.provider(),
                llmStageContent.model(),
                llmStageContent.promptVersion(),
                llmStageContent.usage() == null ? null : llmStageContent.usage().tokenInput(),
                llmStageContent.usage() == null ? null : llmStageContent.usage().tokenOutput(),
                llmStageContent.usage() == null ? null : llmStageContent.usage().latencyMs(),
                llmStageContent.generationMode()
            );
            generationReason = "Generated by LLM successfully.";
        } catch (Exception ex) {
            String fallbackReason = "LLM failed: " + sanitizeReason(ex.getMessage());
            if (!llmProperties.isFallbackToRule()) {
                taskRepository.markAttemptFailed(attemptId, ex.getMessage(), AttemptLlmMetadata.none("LLM"));
                llmCallLogRepository.save(new LlmCallLog(
                    attemptId,
                    "TASK_RUN",
                    llmProperties.getProvider(),
                    llmProperties.getModel(),
                    task.getStage().name(),
                    "unknown",
                    "{\"note\":\"request payload unavailable\"}",
                    "{\"error\":\"" + sanitizeReason(ex.getMessage()) + "\",\"finish_reason\":\"error\"}",
                    "{}",
                    "FAILED",
                    null,
                    null,
                    null
                ));
                throw ex;
            }
            generated = generateByStage(task);
            metadata = AttemptLlmMetadata.none("TEMPLATE_FALLBACK");
            generationReason = fallbackReason;
        }

        String outputJson = writeJson(generated);
        taskRepository.markAttemptSucceeded(attemptId, outputJson, metadata);

        if ("LLM".equals(metadata.generationMode())) {
            llmCallLogRepository.save(new LlmCallLog(
                attemptId,
                "TASK_RUN",
                metadata.llmProvider(),
                metadata.llmModel(),
                promptKey,
                metadata.promptVersion(),
                toJson(llmStageContent == null ? null : llmStageContent.requestPayload()),
                toJson(buildResponseSummary(llmStageContent == null ? null : llmStageContent.responsePayload())),
                outputJson,
                "SUCCEEDED",
                metadata.latencyMs(),
                metadata.tokenInput(),
                metadata.tokenOutput()
            ));
        }

        task.markSucceeded(outputJson);
        return toResponse(task, metadata.generationMode(), generationReason, generated);
    }

    private boolean hasOutput(String outputJson) {
        return outputJson != null && !outputJson.isBlank() && !"null".equalsIgnoreCase(outputJson.trim());
    }

    private JsonNode parseOutput(String outputJson) {
        try {
            return objectMapper.readTree(outputJson);
        } catch (Exception ex) {
            throw new InternalServerException("Stored output_json is invalid.");
        }
    }

    private String writeJson(JsonNode output) {
        try {
            return objectMapper.writeValueAsString(output);
        } catch (Exception ex) {
            throw new InternalServerException("Failed to serialize task output.");
        }
    }

    private String toJson(JsonNode node) {
        if (node == null || node.isNull() || node.isMissingNode()) {
            return "{\"note\":\"payload missing\"}";
        }
        return writeJson(node);
    }

    private JsonNode buildResponseSummary(JsonNode responsePayload) {
        if (responsePayload == null || responsePayload.isNull() || responsePayload.isMissingNode()) {
            return objectMapper.valueToTree(Map.of("note", "response payload missing"));
        }
        JsonNode usage = responsePayload.path("usage");
        String finishReason = responsePayload.path("choices").path(0).path("finish_reason").asText(null);
        String content = responsePayload.path("choices").path(0).path("message").path("content").asText("");
        if (content.length() > 1000) {
            content = content.substring(0, 1000);
        }
        return objectMapper.valueToTree(Map.of(
            "usage", usage.isMissingNode() ? objectMapper.createObjectNode() : usage,
            "finish_reason", finishReason == null ? "" : finishReason,
            "choices", List.of(Map.of("message", Map.of("content", content)))
        ));
    }

    private RunTaskResponse toResponse(Task task, String generationMode, String generationReason, JsonNode output) {
        return new RunTaskResponse(
            task.getId(),
            task.getStage().name(),
            task.getNodeId(),
            TaskStatus.SUCCEEDED.name(),
            generationMode,
            generationReason,
            output
        );
    }

    private String sanitizeReason(String reason) {
        if (reason == null || reason.isBlank()) {
            return "unknown error";
        }
        return reason.replace("\"", "'");
    }

    private StageContent generateByLlm(Task task, Long userId) {
        if (!llmProperties.isReady() || !llmProperties.isEnabled()) {
            throw new InternalServerException("LLM is disabled.");
        }
        LearningSession session = (userId == null
            ? sessionRepository.findById(task.getSessionId())
            : sessionRepository.findByIdAndUserPk(task.getSessionId(), userId))
            .orElseThrow(() -> new NotFoundException("Session or task not found."));
        ConceptNode node = conceptNodeRepository.findById(task.getNodeId())
            .orElseThrow(() -> new NotFoundException("Session or task not found."));
        Mastery mastery = masteryRepository.findByUserIdAndNodeId(session.getUserId(), node.getId()).orElse(null);

        StageGenerationContext context = new StageGenerationContext(
            task.getId(),
            task.getSessionId(),
            session.getChapterId(),
            node.getId(),
            node.getName(),
            task.getStage(),
            task.getObjective(),
            null,
            mastery == null ? null : mastery.getMasteryValue()
        );
        return stageContentGenerator.generate(context);
    }

    private JsonNode generateByStage(Task task) {
        return switch (task.getStage()) {
            case STRUCTURE -> objectMapper.valueToTree(Map.of(
                "title", "核心结构图",
                "summary", "先明确定义和边界，再梳理关键关系，最后形成可执行学习路径。",
                "key_points", List.of("定义与边界", "核心流程", "输入输出关系"),
                "common_misconceptions", List.of("只记结论不看条件", "忽略异常路径"),
                "suggested_sequence", List.of("先定义", "再机制", "后练习")
            ));
            case UNDERSTANDING -> objectMapper.valueToTree(Map.of(
                "concept_explanation", "该知识点强调在特定条件下的状态变化机制，核心在于识别触发条件和结果。",
                "analogy", "可以把它看成交通信号系统：条件变化就会切换状态并触发下一步动作。",
                "worked_example", "示例：先给定输入条件，再逐步判断中间状态，最终得出可验证输出。",
                "step_by_step_reasoning", List.of("识别前置条件", "判断状态变化", "验证最终结果"),
                "common_errors", List.of("跳过中间状态", "把必要条件当充分条件"),
                "check_questions", List.of("哪个条件是触发点？", "状态变化顺序是什么？")
            ));
            case TRAINING -> objectMapper.valueToTree(Map.of(
                "questions", List.of(
                    Map.of("id", "q1", "type", "BASIC", "question", "请解释该知识点的核心定义。", "reference_points", List.of("定义", "适用条件"), "difficulty", "EASY"),
                    Map.of("id", "q2", "type", "APPLICATION", "question", "给定一个场景，说明该知识点如何应用。", "reference_points", List.of("步骤", "结果"), "difficulty", "MEDIUM"),
                    Map.of("id", "q3", "type", "REASONING", "question", "当条件变化时，推导状态变化并解释原因。", "reference_points", List.of("推导链路", "边界条件"), "difficulty", "HARD")
                )
            ));
            case REFLECTION -> objectMapper.valueToTree(Map.of(
                "reflection_prompt", "请回顾你在哪一步最容易出错，并说明你准备如何避免。",
                "review_checklist", List.of("能否复述核心概念", "能否解释关键推理", "能否识别常见误区"),
                "next_step_suggestion", "先重做一题应用题，再做一题推理题，并口头总结 1 分钟。"
            ));
        };
    }
}
