export const APP_COPY = {
  brand: 'Lumina AI',
  tutorLabel: '导师',
  loginCta: '登录后继续',
  logoutCta: '退出',
  appBarSignedInHint: '继续这轮学习',
} as const

export const AUTH_COPY = {
  eyebrow: '学习工作流',
  heroTitle: '登录后，继续这轮学习。',
  heroSubtitle: '保留目标、进度和结果；回来时直接接着走。',
  helper: '输入账号后继续。',
  submitLogin: '登录并继续',
  submitRegister: '注册并继续',
  tabLogin: '登录',
  tabRegister: '注册',
  labelUsername: '账号名',
  labelPassword: '密码',
  placeholderUsername: '3-32 位，支持 a-z / 0-9 / _',
  placeholderPassword: '至少 6 位',
  processing: '处理中…',
  toastMissingCredentials: '请输入账号名和密码',
  highlights: [
    { kicker: '目标', title: '继续目标', body: '回到上次选中的知识点。' },
    { kicker: '进度', title: '继续进度', body: '直接回到当前这一步。' },
    { kicker: '结果', title: '继续结果', body: '这轮结果也会保留。' },
  ],
} as const

export const GOAL_COPY = {
  eyebrow: '学习入口',
  title: '开始这轮 AI 学习流程',
  subtitle: '先选主题，下一步进入诊断定位。',
  flowTitle: '当前流程',
  flowSteps: ['目标', '诊断', '规划', '执行', '报告'],
  continueTitle: '继续上次进度',
  continueEmpty: '还没有上次进度',
  continueEmptyHint: '开始后，这里会保留最近一轮。',
  continueLoginTitle: '登录后可继续上次学习',
  continueLoginHint: '学习记录会自动保留在账号里。',
  continueCardHint: '辅助入口',
  footerTitle: '本轮起点',
  footerHint: '确认后将直接进入诊断，生成这轮学习起点。',
  footerNextLabel: '下一步',
  footerNextValue: '进入诊断定位',
  loginToast: '登录后继续',
  subjectSection: '先选学科',
  topicSection: '再选这轮主题',
  topicSectionHint: '确认后就从这个主题开始。',
  topicStartTag: '本轮从这里开始',
  demoHint: '当前每科开放 1 个演示主题',
  representativePoints: '本轮可选方向',
  continueCta: '继续学习',
  noProgressBody: '这次开始后，这里会保留你的最近一轮学习。',
  loginCta: '登录',
  comingSoon: '即将开放',
  transition: '正在进入下一步…',
  ctaStart: '开始这轮学习',
  ctaLogin: '登录后开始这轮',
  toastStart: '登录后就能开始这一轮',
  continueResult: '继续上次：回到这轮学习结果',
  continueProgress: '继续上次：回到刚才的学习进度',
  currentSubjectPrefix: '当前学科：',
} as const

export const DIAGNOSIS_COPY = {
  title: '回答 3 个问题',
  subtitle: '选最贴近的一项即可。',
  topicLabel: '本轮主题',
  intro: '答完进入下一步。',
  submit: '继续下一步',
  loading: '正在准备快速定位…',
  transition: '我正在根据你的回答整理思路，马上就好…',
  qFoundation: '你对这个内容现在大概处于什么状态？',
  qBlocker: '你现在最大的困难更像哪一种？',
  qPrefix: '第',
  qSuffix: '题',
  q3: '你这次想怎么推进？',
  toastSelectQ1: '请选择第 1 题',
  toastSelectQ2: '请选择第 2 题',
  toastSelectQ3: '请选择第 3 题',
  toastSubmitFail: '提交失败，请重试',
  retry: '重试',
} as const

export const PLAN_COPY = {
  loading: '正在整理这轮路径...',
  reload: '重新加载',
  whyFirst: '为什么从这里开始',
  currentAdvice: '当前建议',
} as const

export const EXECUTION_COPY = {
  redirectKicker: '跳转中',
  redirectTitle: '正在进入执行页',
  redirectSubtitle: '马上带你回到当前任务。',
  noTaskToast: '当前没有任务，先回到规划页。',
  noTaskEmpty: '当前没有任务',
  viewReport: '查看结果',
  loadingTask: '正在打开当前任务...',
  feedbackTitle: '当前反馈',
  transcriptUser: '你的回答',
  transcriptAssistant: '反馈',
  railTitle: '按顺序推进 4 个知识点',
  railOverview: '每次只推进当前这一个点。',
  mainActionWhy: '现在先做',
  actionChips: '这样开头',
  passHint: '写到这里就能继续',
  supportToggle: '需要时再看',
  supportTranscript: '本步记录',
  currentFocus: '当前重点',
  done: '已经做到',
  gap: '还要补',
  nextStep: '现在继续',
  taskHeaderKicker: '这一屏先做',
  currentTaskSingleThing: '这一步只做一件事：',
  currentTaskDoNow: '你现在要做的是：',
  completionCriteriaTitle: '完成标准',
  backToPlan: '回规划',
} as const

export const REPORT_COPY = {
  title: '本轮结果',
  subtitle: '看结果，然后决定下一步。',
  loading: '正在整理结果…',
  result: '本轮结果',
  summary: '这一轮总结',
  nextAction: '下一步',
  confirmNext: '选择下一步',
  confirmAction: '继续',
  restart: '重新开始',
  replanHint: '建议先重新规划。',
  goalReview: '目标回顾',
  completedProgress: '已完成进展',
  unresolvedIssues: '待解决问题',
  evidenceSummary: '证据摘要',
  summarySection: '总结',
  learningMethod: '学习方法表现',
  learningMethodHint: '基于任务内的提问、自我解释与微检查等行为汇总。',
  nextActionSection: '下一步建议',
  replanBanner: '建议重新规划学习路径',
  confirmCardTitle: '确认下一步',
  confirmCardHint: '请选择你打算执行的下一步动作',
  confirmSubmit: '确认并继续',
  nextHintDefault: '已确认下一步',
  toastReplan: '建议重新规划，请从目标输入重新开始',
  methodQuestioning: '提问质量：',
  methodSelfExplain: '自我解释：',
  methodCheck: '微检查：',
  methodPositive: '正向信号：',
  methodAnti: '需注意：',
  methodNextAdvice: '下一轮建议：',
  submitted: '已提交',
  notDetected: '未检测到',
  passed: '通过',
  partialFail: '部分未通过',
  retry: '重试',
} as const

export const TASKRUN_COPY = {
  loading: '正在打开当前任务…',
  retry: '重试',
  empty: '当前没有任务',
  emptyHint: '先完成规划或从目标页重新开始。',
  viewReport: '查看结果',
  scaffoldLoadingPrefix: '正在加载',
  scaffoldLoadingSuffix: '…',
  scaffoldNoAction: '当前没有可执行的学习动作，请刷新后重试。',
  defaultMyAnswer: '我的回答',
  defaultMyExpression: '我的表达',
  advancePhase: '进入下一阶段',
} as const
