-- Enum types
DO $$ BEGIN
  CREATE TYPE task_stage AS ENUM ('STRUCTURE','UNDERSTANDING','TRAINING','REFLECTION');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE run_status AS ENUM ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
