package navigator.api;

public enum BusinessErrorCode {
    RESOURCE_NOT_FOUND,
    DIAGNOSIS_NOT_COMPLETED,
    PLAN_NOT_COMMITTED,
    TASK_NOT_CURRENT,
    TASK_ALREADY_COMPLETED,
    SESSION_NOT_COMPLETED,
    SESSION_ALREADY_COMPLETED,
    DIAGNOSIS_ALREADY_COMPLETED,
    PLAN_ALREADY_COMMITTED,
    INVALID_ARGUMENT,
    INVALID_REQUEST,
    INTERNAL_ERROR,
    UNAUTHORIZED,
    USERNAME_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    FORBIDDEN,
    TASK_EXECUTION_NOT_READY_FOR_COMPLETE,
    INVALID_TASK_EXECUTION_STATE,
    TASK_CLOSURE_INCOMPLETE
}
